### ISSUE TITLE
Reference ordering starts with Figure and Table captions

### ISSUE THREAD

**Issue by Alkusoittow** [matthewfeickert/Dedman-Thesis-Latex-Template#1]
Because the "List of Figures" and "List of Tables" appears before the main body of text, any references in captions will force the numbering in the bibliography to start with them.  This means that the first reference in the main body of text may be something other than 1.  To correct this issue, please introduce the following line at the top of the packages.tex file:

\usepackage{notoccite}

Any previously created *.bbl files will need to be manually deleted, and the entire project recompiled.  But for new versions, this shouldn't be a problem.

**Comment by matthewfeickert** [comment]
Closed by PR #2. Thanks for reporting, @Alkusoittow.
