### ISSUE TITLE
Archiving this project and moving to the fork under the account "stephensekula"

### ISSUE THREAD

**Issue by stephensekula** [matthewfeickert/Dedman-Thesis-Latex-Template#104]
Hi Matthew,

As we discussed, it makes sense to "transfer" this project over to my user account on Github since you are no longer at SMU and, as Dept. Chair, my account makes a "safe choice" for hosting this repository until SMU provides their own Git solution.

To do this, we should archive your project and make it read only, and direct new users/old users to switch to the remote under my account. Please let me know how and when you want to proceed on this. My fork is full up-to-date with yours.

Regards,
Steve

**Comment by matthewfeickert** [comment]
> To do this, we should archive your project and make it read only, and direct new users/old users to switch to the remote under my account. 

SGTM @stephensekula. Seems that I already updated the CI to GHA in PR #102, so I should probably just do some housekeeping checks to make sure everything still works and then I'll archive and ping you.

We should also have your fork get detached from mine after that, as the default behavior is to have PR submitted to a fork target back to the parent project (not desired here as it is a break off fork). Luckily, if you email GitHub they will manually go in and sever forks from parents.

As it seems like things are already mostly done can you ping me on Monday (2021-08-09) if I don't have this all checked off?

**Comment by matthewfeickert** [comment]
@stephensekula Alternative idea: I just transfer the ownership of the project to you. That's easier on basically every front.

**Comment by stephensekula** [comment]
Can do! Give me one second.

**Comment by stephensekula** [comment]
Done. Ready when you are.

**Comment by matthewfeickert** [comment]
![success](https://user-images.githubusercontent.com/5142394/128583902-a00ceea1-bbb0-4d79-b5ee-f3c90894a04c.png)

:rocket:

**Comment by stephensekula** [comment]
Silly question: this project still appears under your Github account and not mine. Is that the correct behavior?

**Comment by stephensekula** [comment]
To put this in perspective, all links to https://github.com/stephensekula/Dedman-Thesis-Latex-Template/ are inherently broken because this doesn't exist. Visiting that page gets the 404 error.

**Comment by stephensekula** [comment]
Never mind. There was an email about the transfer needing approval but not a notification in Github. All done!

**Comment by matthewfeickert** [comment]
> All done!

:rocket: 

@stephensekula I've [forked the project again](https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template) so that anything that had my original URL will still build into the future. If you have any questions on how things work just let me know and I'm happy to both discuss and/or try to help our with PRs. :+1:
