### ISSUE TITLE
Request: Add nowidow package

### ISSUE THREAD

**Issue by Alkusoittow** [matthewfeickert/Dedman-Thesis-Latex-Template#11]
Just a suggestion to add the nowidow package to the template.  This automatically looks for and corrects orphaned and widowed lines in the document.  All that's needed is the following line added to customcommands.tex:

```latex
\usepackage[all]{nowidow}
```

This does NOT correct ((sub)sub)section headers from appearing as the last line of text on a page, but it helps with everything else!

**Comment by matthewfeickert** [comment]
I'll add this in later today.

@egodat, I think this might resolve some of the issues you were seeing as well.

**Comment by matthewfeickert** [comment]
@Alkusoittow I'm going to assume the answer is no and merge the PR in. Thanks for the suggestion --- it is a good one!
