### ISSUE TITLE
Paper numbering issue in .sty file

### ISSUE THREAD

**Issue by Alkusoittow** [matthewfeickert/Dedman-Thesis-Latex-Template#20]
There are a few minor issues in the style file which hard-code certain page numbering schemes. These issues cropped up during my format check (Spring 2018).  Requirements may change in the future, but for now, the following needs to be modified:

- In the copyright environment section, set the following:
```latex
\setcounter{page}{0}
```
This removes the roman numeral page counter at the bottom.  This is required per the format check.

- In the acknowledgements section, change to the following:
```latex
\setcounter{page}{4}
```
This sets the roman counter to “iv” on this page, as it ought to be page 4.

- This next one is tricky.  In the abstract section, I’ve had to hard code:
```latex
\setcounter{page}{6}
```
because my acknowledgements were 2 pages long.  If your acknowledgements are 1 page or 3+ pages, this won't work and you'll need to hard-code accordingly.  _Perhaps a variable can be used here_.  You cannot just remove this line of code either (hoping that the counter would increment automatically).  If you do, the numeral at the bottom of the page is "i" which is incorrect.

Fortunately, the Table of Contents and List of (Figures/Tables) follows correctly from this point on.

**Comment by matthewfeickert** [comment]
@Alkusoittow Thanks for raising the Issue. Any chance we could get you to add some screenshots of the pdf output of the "failing" and "passing" cases?

**Comment by matthewfeickert** [comment]
@Alkusoittow @egodat Can you comment on what exactly the format check is enforcing? I'm trying to just fix the `DL_thesis.sty` to automatically handle all of this, but I need to know what pages are supposed to have what style (roman or arabic) and what numbers (specifically, where is the 0 page supposed to start, so I know what is supposed to be the first numbered page).

**Comment by matthewfeickert** [comment]
In summary, this was being caused by the `\setcounter{page}{0}` being used multiple times in different commands in `DL_thesis.sty`.
