### ISSUE TITLE
Maximum Figure Width

### ISSUE THREAD

**Issue by danjardin** [matthewfeickert/Dedman-Thesis-Latex-Template#29]
I would like to set a max figure width so that they do not exceed the width of the page, otherwise the original image size can be used. The [second answer (one by egreg)](https://tex.stackexchange.com/a/47252/152544) on this page [https://tex.stackexchange.com/questions/47245/set-a-maximum-width-and-height-for-an-image](https://tex.stackexchange.com/questions/47245/set-a-maximum-width-and-height-for-an-image) looks like a clean solution that does exactly what I want.

I see that `\usepackage{adjustbox}` is already included in `Dedman-Thesis-Latex-Template/latex/packages.tex`, but without the `[export]` option.

Two possible solutions: add the `[export]` option in the template source code and push the change, or allow `user_commands.tex` to override anything in `packages.tex` so that I can import my own desired packages regardless of their presence in `packages.tex`.

**Comment by matthewfeickert** [comment]
@danjardin Thanks for the Issue! What you've suggested is all reasonable, so I think that we should ideally do both. That is:

- Use [`\usepackage[export]{adjustbox}`](https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template/blob/master/latex/packages.tex#L24) as you've suggested (I see no reason not to). This will be an easy PR. :+1: 
- In a separate Issue consider the addition of a `user_packages.tex` that would be given preference over `Dedman-Thesis-Latex-Template/latex/packages.tex`. A bit tricky, but I don't think impossible.

**Comment by matthewfeickert** [comment]
@danjardin This is in now, so if you run 

```
bash Dedman-Thesis-Latex-Template/update_template.sh
```

you should get it (though you should also commit the updated submodule).
