### ISSUE TITLE
"Bad Substitution" when updating template

### ISSUE THREAD

**Issue by danjardin** [matthewfeickert/Dedman-Thesis-Latex-Template#32]
The command to update the template is `bash Dedman-Thesis-Latex_Template/update_template.sh`, but I'm getting an error about a bad substitution on [line 60](https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template/blob/17d027181cf2a4b4434533c5f0a0b265460eb94d/update_template.sh#L60), specifically `"${response,,}"`. I wonder if MacOS doesn't like the commas there. 

Note: if I give an input such as `bash Dedman-Thesis-Latex-Template/update_template.sh update`, then it runs fine and I get the update anyway.

**Comment by matthewfeickert** [comment]
@danjardin Thanks for reporting this. I'm going to conscript you in debugging this if you don't mind (hence I've assigned you to the Issue as well).

**Comment by matthewfeickert** [comment]
@danjardin Can you tell me what version of Bash you have? That is what is the output of

```
bash --version
```
?

**Comment by danjardin** [comment]
Yup, running bash version 3.2.57

**Comment by matthewfeickert** [comment]
> running bash version 3.2.57

Ah, okay. Yeah this also won't get fixed anytime soon as [Bash 4.0 and later is under GPLv3 (which Apple won't use)](https://apple.stackexchange.com/a/197172).

Okay, I know how to patch this. I'll ping you for testing a fix soon.

**Comment by matthewfeickert** [comment]
@danjardin Can you run the below as a script on your machine?

```bash
#!/usr/bin/env bash

function main {
    printf "Do you want to sync your base LaTeX files with the template? [Y/N]: "
    read -r response
    # MacOS can't use Bash 4.0+, so use old lowercase method
    response="$(echo ${response} | tr [:upper:] [:lower:])"
    if [[ "${response}" == "y" ]]; then
        printf "response is: ${response}\n"
    else
        printf "response is: ${response}.\nNo go!\n\n"
    fi
}

main $1
```

**Comment by danjardin** [comment]
That seems to work fine. Answering with "Y" or "y" runs without error. Anything else and it returned the "No go!" message.

**Comment by matthewfeickert** [comment]
@danjardin Thanks! I think this is wrapped up then, so I'll merge in PR #33.
