### ISSUE TITLE
"update_template.sh install" Overwrites files

### ISSUE THREAD

**Issue by danjardin** [matthewfeickert/Dedman-Thesis-Latex-Template#35]
Running `. Dedman-Thesis-Latex-Template/update_template.sh install` after editing some of the files that are copied will sync those files back to the template and overwrite any of the user's changes. Examples of files this is likely to happen is `Dedman-Thesis-Latex-Template/latex/front_pages.tex`, `latex/user_config.tex`, and `user_thesis.tex`.

The most robust solution that should definitely be put in place is to have the installer check that the files exist before copying them over. Below are a few other suggestions that can also be considered.

It could be stressed that users should change the name of the template files to prevent overwriting files of the same name. An example where this already exists is in the Makefile there is an option to compile `$(USER)_thesis.tex` instead of `user_thesis.tex` that I had not been using. I have made this change now that this issue has happened to me. To facilitate the necessity of changing file names, the example files in the template could also have more generic names such as "temp_*". A good file name is the example bibliography `example.bib`. File names that aren't generic enough and are less likely to be changed are `Dedication.tex`, `Acknowledgements.tex`, `Abstract.tex`, `preface.tex`, `introduction.tex`, and `appendix_A.tex` all in `/src` .

Another personal lesson is that I will try to push all changes to git before I attempt any changes to the template files. Perhaps a warning could be issued whenever a command is run that notifies the user as to which files will be changed before the changes happen. This could be accompanied by a prompt to accept those changes.

**Comment by matthewfeickert** [comment]
@danjardin I believe that this got resolved in PR #37, but let me know if you have additional feedback.
