### ISSUE TITLE
Move front_pages.tex out of Dedman-Thesis-Latex-Template

### ISSUE THREAD

**Issue by danjardin** [matthewfeickert/Dedman-Thesis-Latex-Template#36]
I think that `Dedman-Thesis-Latex-Template/latex/front_pages.tex` should be copied into the user's `/latex` directory.

This script requires changing the names of the dedication, acknowledgement, and abstract files and I don't think the user should have to make any modifications inside of `/Dedman-Thesis-Latex-Template`.

If this change is made, then line 18 of `user_thesis.tex` should correspondingly be changed from

`\input{Dedman-Thesis-Latex-Template/latex/front_pages.tex}`
to
`\input{/latex/front_pages.tex}`

**Comment by danjardin** [comment]
This is tied to issue #35, where I suggested renaming one's own source files. If those files are renamed, then won't they need to be changed in front_pages.tex too so it knows which file to import? Specifically, I'm talking about lines 14, 18, 26, and 29.

**Comment by matthewfeickert** [comment]
Ah, okay yeah there you said

> It could be stressed that users should change the name of the template files to prevent overwriting files of the same name. An example where this already exists is in the Makefile there is an option to compile $(USER)_thesis.tex instead of user_thesis.tex that I had not been using. I have made this change now that this issue has happened to me. To facilitate the necessity of changing file names, the example files in the template could also have more generic names such as `temp_*`.

I'm a bit wary of doing this as this starts to break the default uniformity of the template as it makes the user responsible for management of files that control the style. This breaks the functionality of being able to distribute style updates to all users through a submodule update and makes debugging issues between users much more difficult (instead of identifying which files the issue is happening in we would then need to know their entire directory tree structure).

I think it will just be easier to make sure that if a file is ever going to be overwritten by the install or update script that it first gets explicit user approval at the command line. I can probably setup tests as well that check this in the CI. Thoughts?

**Comment by danjardin** [comment]
> I think it will just be easier to make sure that if a file is ever going to be overwritten by the install or update script that it first gets explicit user approval at the command line. I can probably setup tests as well that check this in the CI.

Not sure what CI stands for, but I definitely think this should be done and it will solve the overwriting problems of issue #35.

I think this particular issue is more about the template philosophy. I know what you mean about keeping the management files separate, but I also feel like the user should have full control over their source files.

Crazy Idea:
How smart can the import lines be? For example, is it possible to search through /src for anything with "awknowledgements" in the name (insensitive of case)? Or, is there a way of determining if it's the acknowledgements regardless of the name of the file? [insert rabbit hole chase scene]

Much Simpler Idea:
Add a comment to the top of some of the source files telling the user not to change the name. This breaks the degeneracy between files that can be renamed like preface.tex, introduction.tex, appendix_A.tex, example.bib, and user_config.tex; and the ones that should not be renamed like dedication.tex, acknowledgements.tex, abstract.tex, and symbols.tex.

It's probably a clear distinction in your mind, but I didn't realize until this conversation that the line between what the user can mess around with and what they shouldn't change is determined by user_thesis.tex. Anything in user_thesis.tex with `\input{src/*}` is fair game. I think the solution to this issue is making that clear to every user, even the latex novices, because the template first starts you off with a handful of files in /src and they need to be treated differently.

**Comment by matthewfeickert** [comment]
@danjardin I believe that this got resolved in PR #37, but let me know if you have additional feedback.
