### ISSUE TITLE
Have consistent formatting of section titles

### ISSUE THREAD

**Issue by matthewfeickert** [matthewfeickert/Dedman-Thesis-Latex-Template#43]
At the moment the chapters, appendices, and glossary all have title formatting that is inconsistent with the rest of the document. This should be standardized.

**Comment by danjardin** [comment]
These titles are also supposed to be in all caps, which is not currently being enforced.

**Comment by matthewfeickert** [comment]
> These titles are also supposed to be in all caps, which is not currently being enforced.

Yeah, you're saying for example that "Preface" should be "PREFACE" and "Chapter 1" should be "CHAPTER 1", yes?

**Comment by danjardin** [comment]
That is correct. See "Headings, TItles, and Subtitles" on pg.8 of [Thesis Guide](https://www.smu.edu/graduate/CurrentStudents/Graduation/DissThesisGuide)

**Comment by matthewfeickert** [comment]
For future self reference (bolding added for emphasis):

> **Headings, Titles, and Subtitles**
>
> Always begin a major division (such as a chapter) at the top of a new page. Center the heading at the top of the page, and **type it entirely in uppercase letters**. Chapter headings or similar main sections should be 2” from the top of the page, rather than the standard 1” margin.
>
> Chapter titles are optional. If you title one chapter, however, then all chapters should have titles. If you type the title in all uppercase letters, this should be reflected in the Table of Contents. Do not type subheadings entirely in uppercase letters. Center chapter titles under the chapter number, one double space below. If the title extends beyond one line, keep the title single-spaced.
>
> Triple space from the chapter title (or from the chapter number if no chapter title is used) to the first line of text. This also applies to the first entry in the Table of Contents and the Bibliography, as well as to the first paragraph in a chapter.

**Comment by danjardin** [comment]
One more point to add here. Forcing the chapter and appendix names to be all caps also needs to be reflected in the TOC. It probably depends on where you enforce the style, but it's possible that latex will not automatically make the same change in the TOC.

**Comment by danjardin** [comment]
This came back up in the most recent format check. The name of every chapter and appendix is supposed to be all caps. Not only that, but the line above that says "Chapter 1" or "Appendix A" also needs to be all caps.

Bad: 
          Chapter 1
    Name of Chapter

Bad:
             Chapter 1
    NAME OF CHAPTER

Good:
            CHAPTER 1
    NAME OF CHAPTER

**Comment by matthewfeickert** [comment]
> The name of every chapter and appendix is supposed to be all caps. Not only that, but the line above that says "Chapter 1" or "Appendix A" also needs to be all caps.

I asked for clarification on this as the [2018 and 2019 Dissertation and Thesis Guide](https://www.smu.edu/-/media/Site/graduate/Dissertation-Guide-2018-2019-v4.pdf?la=en) says that

> Chapter titles are optional. If you title one chapter, however, then all chapters should have titles. **If you type the title in all uppercase letters**, this should be reflected in the Table of Contents. Do not type subheadings entirely in uppercase letters. Center chapter titles under the chapter number, one double space below. If the title extends beyond one line, keep the title single-spaced.

and was told that

> You can omit the note in the format check.

so I think that having the following is okay

![template_TOC](https://user-images.githubusercontent.com/5142394/60402266-da15dc00-9b52-11e9-8adc-05b3a9bf4571.png)
