### ISSUE TITLE
Add example table to thesis template

### ISSUE THREAD

**Issue by matthewfeickert** [matthewfeickert/Dedman-Thesis-Latex-Template#47]
This should be added using the [`booktabs`](https://www.ctan.org/pkg/booktabs) package for style.

Examples of good table design:
- [TeX StackExchange: Tip on how to make a visually good table](https://tex.stackexchange.com/questions/238503/tip-on-how-to-make-a-visually-good-table)
- [Edward Tufte endorsed example from Darkhorse Analytics](https://twitter.com/edwardtufte/status/451820483109847040?lang=en)

**Comment by danjardin** [comment]
@matthewfeickert, you have infinitely more experience with this so I will leave it to your judgement if this is something worth endorsing, but I've been using an [online table generator](https://www.tablesgenerator.com/) to make tables. This provides a simple gui to style the table as you desire, and generates the code that can by dropped right into the source file.

**Comment by matthewfeickert** [comment]
> I've been using an [online table generator](https://www.tablesgenerator.com/) to make tables

Yup. That one has been around for a long time (because it is good). I don't use it as I've written my own generators/have written too many and can do it by hand (:grimacing:), so maybe what I can do is add a mock table that in the caption mentions this resource and links to it.

**Comment by danjardin** [comment]
> I've written my own generators

Show off 😝

But in general, I think the typical user won't be a latex expert so any tools like this that make life easier should definitely be encouraged.

**Comment by matthewfeickert** [comment]
> But in general, I think the typical user won't be a latex expert so any tools like this that make life easier should definitely be encouraged.

Very much agreed. This will for sure go in. :+1:
