### ISSUE TITLE
2" top margins of pre-pages

### ISSUE THREAD

**Issue by danjardin** [matthewfeickert/Dedman-Thesis-Latex-Template#54]
The format reviewer specifically referenced pg.7 of the [Dissertation and Thesis Guide](https://www.smu.edu/graduate/CurrentStudents/Graduation/DissThesisGuide). Most pages in the thesis are to be 1" top margins, but a handful of the pre-pages are supposed to be 2" margins. This is also true for the first page of every chapter, appendix, and bib.

**Comment by matthewfeickert** [comment]
This Issue was originally discussed in Issue #52. Its [thread starts here](https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template/issues/52#issuecomment-475900488).

**Comment by danjardin** [comment]
Reading between the lines here, it says the first page of appendix (singular). However, I would think that multiple appendices should be treated like different chapters, where the heading page of EACH appendix should have 2" top margins.

**Comment by matthewfeickert** [comment]
>  However, I would think that multiple appendices should be treated like different chapters, where the heading page of EACH appendix should have 2" top margins.

@danjardin Yes, I would agree with this interpretation. Do you want to email for explicit clarification?

**Comment by danjardin** [comment]
No, I just wanted to state that here to make it explicitly clear. I also should've checked before writing that because each appendix already does have a 2" margin. Along the same lines, it's not mentioned on pg.7 of the dissertation guide, but the Dedication page also needs to have a 2" margin (see bullet 8 on pg.11) and it looks like this is already being handled correctly.

I've pulled the latest template upgrades and now everything on this list looks like it's correct. Do you think the Preface should also have a 2" margin? It's not explicitly listed in the guide, but it's sometimes kinda-sorta treated like a chapter (and sometimes not). Really the only thing I've seen that isn't supposed to start with 2" is the TOC.

**Comment by matthewfeickert** [comment]
> I also should've checked before writing that because each appendix already does have a 2" margin. 

Kinda. This is currently done in a very hacky way that is not robust and needs to be fixed. This is getting addressed by PR #53. 

> I've pulled the latest template upgrades and now everything on this list looks like it's correct. 

:+1: :rocket: 

> Do you think the Preface should also have a 2" margin? It's not explicitly listed in the guide, but it's sometimes kinda-sorta treated like a chapter (and sometimes not). Really the only thing I've seen that isn't supposed to start with 2" is the TOC.

Yeah, probably. I agree that it is basically a chapter and we should treat it as such until we get told otherwise.

**Comment by danjardin** [comment]
Let it be known that the Preface is considered a chapter and therefore also needs to have a 2" margin at the top. This is the direct word from the most recent format review
