### ISSUE TITLE
Single space committee on signature page

### ISSUE THREAD

**Issue by danjardin** [matthewfeickert/Dedman-Thesis-Latex-Template#55]
Committee members and their positions should be single-spaced on signature page: It seems to be double-spaced if their name or title spills onto a second line.

**Comment by matthewfeickert** [comment]
This Issue was originally discussed in Issue #52. Its [thread starts here](https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template/issues/52#issuecomment-476495208).
