### ISSUE TITLE
Abstract title not all caps

### ISSUE THREAD

**Issue by danjardin** [matthewfeickert/Dedman-Thesis-Latex-Template#56]
Title of abstract should not be all caps, only capitalize first letter of important words. However, the thesis title on the title page should still be all caps. It's easiest if the user writes the title correctly in `user_config.tex` and then is automatically changed to all caps where required.

**Comment by matthewfeickert** [comment]
This Issue was originally discussed in Issue #52. Its [thread starts here](https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template/issues/52#issuecomment-475841136).
