### ISSUE TITLE
Orphans/Widows

### ISSUE THREAD

**Issue by danjardin** [matthewfeickert/Dedman-Thesis-Latex-Template#57]
This might require some digging because the easiest way to avoid orphans & widows is to add `\usepackage[all]{nowidow}`, which has already been included since it was requested in Issue #11.

**Comment by matthewfeickert** [comment]
This Issue was originally discussed in Issue #52. Its [thread starts here](https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template/issues/52#issuecomment-476849671) and [wraps up here](https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template/issues/52#issuecomment-477417938).
