### ISSUE TITLE
Hanging indent in bib

### ISSUE THREAD

**Issue by danjardin** [matthewfeickert/Dedman-Thesis-Latex-Template#58]
Indent after the first line of each bib citation, similar to how the list of figures is handled. This is called a hanging indent, and needs to be applied to the bibliography despite the fact that the bib entries are already numbered and effectively look like a hanging indent already.

**Comment by matthewfeickert** [comment]
This Issue was originally discussed in Issue #52. Its [thread starts here](https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template/issues/52#issuecomment-475840462) and [wraps up here](https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template/issues/52#issuecomment-475841473).
