### ISSUE TITLE
Table of Contents Formatting

### ISSUE THREAD

**Issue by danjardin** [matthewfeickert/Dedman-Thesis-Latex-Template#64]
As mentioned in Issue #43 , the chapter and appendix titles need to be all caps.

Each level should be "indented three character spaces". It's a little difficult to see if this is done properly in the compiled doc, but it looks like it might be <3. This should be checked in the style file.

Headings that run longer than one line should also be indented for all subsequent lines. (Back to the hanging indent in Issue #58 )

**Comment by matthewfeickert** [comment]
@anjardin PR #53 took care of the works "Chapter" and "Appendix" being in caps.
